### PR TITLE
POM tweaks

### PR DESCRIPTION
**Pull request by cdman**
Make JUnit a compile time dependency to avoid forcing users to a specific version and make the classes Java 1.6 compatible.

### CODE REVIEW

**Comment by jvanzyl** [comment]
I will flip this over to the takari lifecycle with its compiler settings. It will also be a minimum of Java 1.7.

**Comment by jvanzyl** [comment]
I will adjust the POM to work with the Takari Lifecycle and then do a release.

**Comment by jvanzyl** [comment]
Ok, I made changes on 55bda03b0b32803419b2bf1e4b60750097f1d964. Let me know if that works for you and I'll cut a release and switch it back to 1.7.

**Comment by jvanzyl** [comment]
@cdman forget to mention you so you would see this.

**Comment by cdman** [comment]
Yes, I'm good, thank you.

**Comment by jvanzyl** [comment]
Ok, i'll release it.

**Pull request closed without merging**
